# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connmeUi.ui'
#
# Created: Tue Apr 15 00:57:28 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setFixedSize(300, 400)
        MainWindow.setMinimumSize(QtCore.QSize(300, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/connme/img/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 76, 281, 311))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.setting = QtGui.QWidget()
        self.setting.setObjectName(_fromUtf8("setting"))
        self.gridLayout = QtGui.QGridLayout(self.setting)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_4 = QtGui.QLabel(self.setting)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_8.addWidget(self.label_4)
        self.label_2 = QtGui.QLabel(self.setting)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_8.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.setting)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_8.addWidget(self.label_3)
        self.label_5 = QtGui.QLabel(self.setting)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_8.addWidget(self.label_5)
        self.label = QtGui.QLabel(self.setting)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_8.addWidget(self.label)
        self.label_6 = QtGui.QLabel(self.setting)
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_8.addWidget(self.label_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.lineEdit_2 = QtGui.QLineEdit(self.setting)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.verticalLayout_7.addWidget(self.lineEdit_2)
        self.comboBox_2 = QtGui.QComboBox(self.setting)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.verticalLayout_7.addWidget(self.comboBox_2)
        self.comboBox = QtGui.QComboBox(self.setting)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.verticalLayout_7.addWidget(self.comboBox)
        self.comboBox_3 = QtGui.QComboBox(self.setting)
        self.comboBox_3.setMaxVisibleItems(3)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.verticalLayout_7.addWidget(self.comboBox_3)
        self.lineEdit = QtGui.QLineEdit(self.setting)
        self.lineEdit.setMaxLength(63)
        self.lineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_7.addWidget(self.lineEdit)
        self.vinterface_cbox = QtGui.QCheckBox(self.setting)
        self.vinterface_cbox.setCheckable(True)
        self.vinterface_cbox.setChecked(False)
        self.vinterface_cbox.setTristate(False)
        self.vinterface_cbox.setObjectName(_fromUtf8("vinterface_cbox"))
        self.verticalLayout_7.addWidget(self.vinterface_cbox)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.setting)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 1)
        self.tabWidget.addTab(self.setting, _fromUtf8(""))
        self.client = QtGui.QWidget()
        self.client.setObjectName(_fromUtf8("client"))
        self.tableWidget = QtGui.QTableWidget(self.client)
        self.tableWidget.setGeometry(QtCore.QRect(-1, -1, 279, 291))
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setWordWrap(False)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.horizontalHeader().setResizeMode(0,QtGui.QHeaderView.Stretch)
        self.tableWidget.horizontalHeader().setResizeMode(0,QtGui.QHeaderView.Interactive)
        self.tableWidget.horizontalHeader().resizeSection(0, 200);
        self.tableWidget.verticalHeader().setVisible(False)
        self.tabWidget.addTab(self.client, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.txt_log = QtGui.QTextEdit(self.tab)
        self.txt_log.setGeometry(QtCore.QRect(0, 0, 277, 279))
        self.txt_log.setReadOnly(True)
        self.txt_log.setObjectName(_fromUtf8("txt_log"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 10, 300, 56))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 56))
        self.frame.setStyleSheet(_fromUtf8("#frame\n"
"{background-image: url(:/connme/img/logo.png);}\n"
"#frame QLabel\n"
"{color: #0b2f57;}"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.lineEdit_3 = QtGui.QLabel(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 33, 151, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Connme", None))
        self.label_4.setText(_translate("MainWindow", "Hotspot Name", None))
        self.label_2.setText(_translate("MainWindow", "Internet to share", None))
        self.label_3.setText(_translate("MainWindow", "Share over", None))
        self.label_5.setText(_translate("MainWindow", "Sharing Mode", None))
        self.label.setText(_translate("MainWindow", "Password", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Open", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Encrypted (WPA)", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Encryptred (WPA2)", None))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Encrypted (WPA/WPA2)", None))
        self.vinterface_cbox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Check this if failed to start hotspot</p></body></html>", None))
        self.vinterface_cbox.setText(_translate("MainWindow", "Virtual Interface", None))
        self.pushButton.setText(_translate("MainWindow", "Start Hotspot", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.setting), _translate("MainWindow", "Setting", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hostname", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Internet", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.client), _translate("MainWindow", "List Client", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Log", None))
        self.lineEdit_3.setText(_translate("MainWindow", "Stopped", None))

import connme_rc
